apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: http-issuer
  namespace: govierno
spec:
  acme:
    email: chile@govierno.cl
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
